name: cdit_cfm_xl2
target: models.dit_cfm_shortcut.DiT_XL_2
params:
  learn_sigma: False
  num_classes: ${data.num_classes}
  in_channels: 8
  class_dropout_prob: 0.0
  use_dt_adaptor: True
  att_type: fsdp
  use_shortcut: True