name: cdit_b2_cdp0
target: models.dit_shortcut.DiT_B_2
params:
  learn_sigma: False
  num_classes: ${data.num_classes}
  in_channels: 4
  class_dropout_prob: 0.0
  use_dt_adaptor: True
  att_type: fsdp
  use_shortcut: True


